---
version: "3.8"
services:

  v2ray:
    image: v2fly/v2fly-core:latest
    container_name: v2ray
    volumes:
      - ./config/v2ray/config.json:/etc/v2ray/config.json
      - ./config/geodata:/usr/share/v2ray
      - ./log/v2ray:/var/log/v2ray
    networks:
      - default
    command: run -config /etc/v2ray/config.json
    restart: unless-stopped

  swag:
    image: linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - URL=${DOMAIN}
      - VALIDATION=http
      - EMAIL=${EMAIL}
    volumes:
      - ./config/nginx:/config/nginx
      - ./config/certs:/config/etc/letsencrypt
      - ./config/www:/config/www
      - ./log/nginx:/config/log/nginx
    networks:
      - default
    ports:
      # Uses 80 port to update certs first, otherwise haproxy cannot works
      - 80:80
    restart: unless-stopped

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    volumes:
      - ./config/haproxy:/usr/local/etc/haproxy:ro
      - ./config/certs/live/${DOMAIN}:/etc/ssl/certs
    networks:
      - default
    ports:
      - 443:443
    restart: unless-stopped

  warp:
    image: e7h4n/cloudflare-warp:latest
    container_name: warp
    networks:
      - default
    volumes:
      - ./config/warp:/var/lib/cloudflare-warp:rw
    restart: unless-stopped


networks:

  default:
    driver: bridge
