---
version: "3.8"
services:

  v2ray:
    image: "${V2RAY_TAG}"
    container_name: v2ray
    environment:
      - TZ=${TZ}
      - SERVER_HOST=${SERVER_HOST}
    volumes:
      - ./etc/v2ray/config.json:/etc/v2ray/config.json
      - ./log/v2ray:/var/log/v2ray
    networks:
      - v2raynet
    command: run -config /etc/v2ray/config.json
    restart: unless-stopped

  swag:
    image: "${NGINX_TAG}"
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - URL=${DOMAIN}
      - VALIDATION=http
      - EMAIL=${EMAIL}
    volumes:
      - ./etc/nginx:/config/nginx
      - ./etc/certs:/config/etc/letsencrypt/live/${DOMAIN}
    networks:
      - v2raynet
    ports:
      # Uses 80 port to update certs
      - 80:80
    restart: unless-stopped

  haproxy:
    image: "${HAPROXY_TAG}"
    container_name: haproxy
    environment:
      - TZ=${TZ}
    volumes:
      - ./etc/haproxy:/usr/local/etc/haproxy:ro
      - ./etc/certs:/etc/ssl/certs
    networks:
      - v2raynet
    ports:
      # V2Ray port
      - ${PORT}:443
    restart: unless-stopped

  warp:
    image: e7h4n/cloudflare-warp:latest
    container_name: warp
    networks:
      - v2raynet
    volumes:
      - $HOME/.warp:/var/lib/cloudflare-warp:rw
    restart: unless-stopped


networks:

  v2raynet:
    driver: bridge
