---
version: "3.8"
services:

  v2ray:
    image: "${V2RAY_TAG}"
    container_name: v2ray
    environment:
      - TZ=${TZ}
    volumes:
      - ./etc/v2ray/config.json:/etc/v2ray/config.json
      - ./log/v2ray:/var/log/v2ray
    networks:
      - v2raynet
    restart: unless-stopped

  swag:
    image: "${NGINX_TAG}"
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      # Request certs from LetsEncrypt
      - URL=${DOMAIN}
#      - SUBDOMAINS=www,
      - VALIDATION=http
      - EMAIL=${EMAIL}
      # CertBot verify plugins and config options
#      - DNSPLUGIN=cloudflare
#      - PROPAGATION= #optional
#      - DUCKDNSTOKEN= #optional
#      - ONLY_SUBDOMAINS=false #optional
#      - EXTRA_DOMAINS= #optional
#      - STAGING=false #optional
#      - MAXMINDDB_LICENSE_KEY= #optional
    volumes:
#      - ./www:/config/nginx/www
      - ./etc/nginx/nginx.conf:/config/nginx/nginx.conf
      - ./etc/nginx/site-confs:/config/nginx/site-confs
      # Only mount folder to get priv-fullchain-bundle.pem
      - ./etc/certs:/config/etc/letsencrypt/live/${DOMAIN}
      # If you need all certs, please enable this config
#      - ./etc/letsencrypt:/config/etc/letsencrypt/live
    networks:
      - v2raynet
    ports:
      # Uses 80 port to update certs
      - 80:80
    restart: unless-stopped

  haproxy:
    image: "${HAPROXY_TAG}"
    container_name: haproxy
    environment:
      - TZ=${TZ}
    volumes:
      - ./etc/haproxy:/usr/local/etc/haproxy:ro
      - ./etc/certs:/etc/ssl/cert
#      - ./etc/letsencrypt/live/${DOMAIN}:/etc/ssl/cert
    networks:
      - v2raynet
    ports:
      # V2Ray port
      - ${PORT}:443
    depends_on:
      - swag
      - v2ray
    restart: unless-stopped


networks:

  v2raynet:
    driver: bridge
