---
version: "3.8"
services:

  v2ray:
    image: v2fly/v2fly-core:latest
    container_name: v2ray
    volumes:
      - ./config/v2ray/config.json:/etc/v2ray/config.json
      - ./config/geodata:/usr/share/v2ray
      - ./config/certs:/etc/letsencrypt
    networks:
      - default
    command: run -config /etc/v2ray/config.json
    restart: unless-stopped

  swag:
    image: linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - URL=${DOMAIN}
      - SUBDOMAINS=${V2RAY_SUB},${OCSERV_SUB}
      - ONLY_SUBDOMAINS=true
      - VALIDATION=http
      - EMAIL=${EMAIL}
    volumes:
      - ./config/nginx:/config/nginx
      - ./config/certs:/config/etc/letsencrypt
      - ./config/www:/config/www
    networks:
      - default
    ports:
      # Uses 80 port to update certs first, otherwise haproxy cannot works
      - 80:80
    restart: unless-stopped

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    volumes:
      - ./config/haproxy:/usr/local/etc/haproxy:ro
      - ./config/certs:/etc/letsencrypt
    networks:
      - default
    ports:
      - 443:443
    restart: unless-stopped

  warp:
    image: e7h4n/cloudflare-warp:latest
    container_name: warp
    networks:
      - default
    volumes:
      - ./config/warp:/var/lib/cloudflare-warp:rw
    restart: unless-stopped

  ocserv:
    image: duckduckio/ocserv:latest
    container_name: ocserv
    environment:
      - WAIT_HOSTS=swag:443
      - WAIT_FILES=./config/certs/live/${OCSERV_SUB}.${DOMAIN}/fullchain.pem
      - WAIT_HOSTS_TIMEOUT=300
    volumes:
      - ./config/ocserv:/etc/ocserv
      - ./config/certs:/etc/letsencrypt
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges
    networks:
      - default
    restart: unless-stopped


networks:

  default:
    driver: bridge
