name: build_ss_rust_image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'images/ss-rust/**'

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ss-rust
        uses: docker/build-push-action@v5
        with:
          context: ./images/ss-rust
          platforms: linux/amd64,linux/arm64
          push: true
          tags: pandasrun/ss-rust:latest
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PACKAGE_TOKEN }}
      -
        name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: ./images/ss-rust
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ vars.REPO_OWNER_LOWER }}/ss-rust:latest
